### ISSUE TITLE
运行predict.py时提示维度和模型加载错误

### ISSUE THREAD

**Issue by lzl32947** [bubbliiiing/ssd-keras#1]
您好，在下载并安放好```ssd_weights.h5```到```model_data```后并运行predict.py时，出现以下错误：
```

tracking <tf.Variable 'conv4_3_norm/conv4_3_norm_gamma:0' shape=(38,) dtype=float32> gamma
Traceback (most recent call last):
  File "G:\Pycharm Projects\ssd-keras-master\ssd.py", line 64, in generate
    self.ssd_model = load_model(model_path, compile=False)
  File "C:\Users\home\Anaconda3\lib\site-packages\keras\engine\saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "C:\Users\home\Anaconda3\lib\site-packages\keras\engine\saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "C:\Users\home\Anaconda3\lib\site-packages\keras\engine\saving.py", line 270, in _deserialize_model
    model_config = h5dict['model_config']
  File "C:\Users\home\Anaconda3\lib\site-packages\keras\utils\io_utils.py", line 318, in __getitem__
    raise ValueError('Cannot create group in read-only mode.')
ValueError: Cannot create group in read-only mode.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\home\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1607, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 512 and 38 for 'conv4_3_norm/mul' (op: 'Mul') with input shapes: [?,38,38,512], [38].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:/Pycharm Projects/ssd-keras-master/predict.py", line 5, in <module>
    ssd = SSD()
  File "G:\Pycharm Projects\ssd-keras-master\ssd.py", line 38, in __init__
    self.generate()
  File "G:\Pycharm Projects\ssd-keras-master\ssd.py", line 66, in generate
    self.ssd_model = ssd.SSD300(self.model_image_size, self.num_classes)
  File "G:\Pycharm Projects\ssd-keras-master\nets\ssd.py", line 28, in SSD300
    net['conv4_3_norm'] = Normalize(20, name='conv4_3_norm')(net['conv4_3'])
  File "C:\Users\home\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "G:\Pycharm Projects\ssd-keras-master\nets\ssd_layers.py", line 25, in call
    output *= self.gamma
  File "C:\Users\home\Anaconda3\lib\site-packages\tensorflow_core\python\ops\math_ops.py", line 912, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\Users\home\Anaconda3\lib\site-packages\tensorflow_core\python\ops\math_ops.py", line 1206, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "C:\Users\home\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py", line 6701, in mul
    "Mul", x=x, y=y, name=name)
  File "C:\Users\home\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\home\Anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\home\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\home\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Users\home\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1770, in __init__
    control_input_ops)
  File "C:\Users\home\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 512 and 38 for 'conv4_3_norm/mul' (op: 'Mul') with input shapes: [?,38,38,512], [38].
```
运行环境为:
```
tensorflow-gpu==1.15.0
keras==2.3.1
```
此外，在拉取仓库后，程序并不能直接运行，在```ssd.py```第61行没有导入load_model函数：
```
60:          try:
61:->            self.ssd_model = load_model(model_path, compile=False)
62:          except:
```
在67行提示变量```num_anchors```未声明:
```
66:    assert self.ssd_model.layers[-1].output_shape[-1] == \
67:->                     num_anchors / len(self.ssd_model.output) * (self.num_classes + 5), \
68:                    'Mismatch between model and given anchor and class sizes'
```

**Comment by bubbliiiing** [comment]
考虑更改一下keras的版本2.1.5
这个地方的思路是先执行load_model(model_path, compile=False)如果失败则执行
self.ssd_model = ssd.SSD300(self.model_image_size,self.num_classes)
self.ssd_model.load_weights(self.model_path,by_name=True)
如果还失败则判定错误

可能因为keras版本不对应产生问题，你这个是在构建SSD模型的时候出现了tensor不匹配

代码虽然有点问题但是是可以正常执行的，实际上只保留
self.ssd_model = ssd.SSD300(self.model_image_size,self.num_classes)
self.ssd_model.load_weights(self.model_path,by_name=True)
就行

**Comment by lzl32947** [comment]
上午跟踪了一下，发现问题出在```ssd_layers.py```中
```
9:         if K.image_dim_ordering() == 'tf':
10:            self.axis = 3
11:        else:
12:            self.axis = 1
```
高版本的keras废弃了```image_dim_ordering()```函数，因此我手动改为```image_data_format()```，而由于变更的原因使得后面的图像轴出现了错误，高版本keras中可以改为:
```
        if K.image_data_format() == 'channels_first':
            self.axis = 1
        else:
            self.axis = 3
```
问题已经找到，非常感谢！
